on:
  push:
    branches:
    - master
    - release/*
name: Deploy Hugo to Firebase
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: morocarlo/hugo-blog@master
      with:
        firebase-token: ${{ secrets.firebase_token }}
